import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  slide: { width, alignItems: 'center', justifyContent: 'center', padding: 24 },
  iconContainer: {
    padding: 32,
    borderRadius: 40,
    marginBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10
  },
  title: { fontSize: 28, color: '#0f172a', marginBottom: 16, textAlign: 'center', fontFamily: 'Manrope_700Bold'},
  description: { fontSize: 16, color: '#64748b', textAlign: 'center', lineHeight: 24, fontFamily: 'Manrope_400Regular', },
  footer: { padding: 24, paddingBottom: 40 },
  dotsContainer: { flexDirection: 'row', justifyContent: 'center', gap: 8, marginBottom: 24 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#cbd5e1' },
  dotActive: { width: 32, backgroundColor: '#3b82f6' },
  buttonsRow: { flexDirection: 'row', gap: 12 },
  skipButton: { flex: 1, padding: 16, borderRadius: 16, backgroundColor: '#e2e8f0', alignItems: 'center', justifyContent: 'center' },
  skipButtonText: { fontSize: 16, fontWeight: '600', color: '#475569' },
  nextButton: { flex: 1, borderRadius: 16, overflow: 'hidden' },
  nextButtonGradient: { flexDirection: 'row', padding: 16, alignItems: 'center', justifyContent: 'center', gap: 8 },
  nextButtonText: { fontSize: 16, fontWeight: '600', color: '#fff' },
  header: { padding: 24, paddingTop: 60, paddingBottom: 40, borderBottomLeftRadius: 32, borderBottomRightRadius: 32 },
  headerTitle: { fontSize: 32, fontWeight: 'bold', color: '#fff', marginBottom: 8, fontFamily: 'Manrope_700Bold' },
  headerSubtitle: { fontSize: 16, color: 'rgba(255,255,255,0.8)', fontFamily: 'Manrope_400Regular', },
  formContent: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
  },
  inputGroup: { marginBottom: 20 },
  label: { fontSize: 14, fontWeight: '600', color: '#475569', marginBottom: 8 },
  required: { color: '#ef4444' },
  optional: { color: '#94a3b8', fontSize: 12, fontWeight: 'normal' },
  input: { backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 16, padding: 16, fontSize: 16, color: '#0f172a' },
  inputError: { borderColor: '#ef4444' },
  errorRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  errorText: { color: '#ef4444', fontSize: 12 },
  pickerContainer: { backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 16, overflow: 'hidden' },
  picker: { height: 50, width: '100%', color: '#0f172a' },
  pickerItem: { color: '#0f172a' },
  checkboxRow: { flexDirection: 'row', gap: 12, alignItems: 'flex-start', backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 16, padding: 14, marginBottom: 20 },
  checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: '#cbd5e1', alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  checkboxActive: { backgroundColor: '#3b82f6', borderColor: '#3b82f6' },
  checkboxTextWrap: { flex: 1 },
  checkboxTitle: { fontSize: 14, fontWeight: '700', color: '#0f172a', marginBottom: 2 },
  checkboxSubtitle: { fontSize: 12, color: '#64748b', lineHeight: 17 },
  themeRow: { flexDirection: 'row', gap: 12 },
  themeCard: { flex: 1, borderWidth: 2, borderColor: '#e2e8f0', borderRadius: 16, padding: 16, alignItems: 'center', backgroundColor: '#f8fafc' },
  themeCardActive: { borderColor: '#3b82f6', backgroundColor: '#eff6ff' },
  themeText: { marginTop: 8, fontSize: 14, fontWeight: '600', color: '#475569' },
  checkBadge: { position: 'absolute', top: 8, right: 8, width: 20, height: 20, borderRadius: 10, backgroundColor: '#3b82f6', alignItems: 'center', justifyContent: 'center' },
  submitButton: { backgroundColor: '#3b82f6', padding: 16, borderRadius: 16, alignItems: 'center', marginTop: 12 },
  submitButtonDisabled: { opacity: 0.5 },
  submitButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
});
